server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path:
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/duokoala"
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600 #insecond = 1 hours
  refreshable-duration: 360000 #insecond = 100 hours