server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path:
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/duokoala"
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: EMAIL=Duokoala.official@gmail.com
    password: PASSWORD=lxguesiehllqnlne
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
#      ddl-auto: update
#    show-sql: true
  redis:
    host: localhost
    port: 6379
jwt:
  signerKey: SIGNER_KEY=9lg678a/5OweZHwtBKEjPfrwqe0wybmY0f67oNtqziI1UUSMM40iyrb481pdaf82
  valid-duration: 3600 #insecond = 1 hours
  refreshable-duration: 360000 #insecond = 100 hours