server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path:
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/duokoala"
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
#      ddl-auto: update
#    show-sql: true
  redis:
#    host: "redis-15490.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com"
#    port: 15490
#    password: "TDeW3KPTlAhdpdROTzv9sJjD9wSC5K0b"
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600 #insecond = 1 hours
  refreshable-duration: 360000 #insecond = 100 hours
otp:
  valid-for-verification-duration: 60
  valid-for-usage-duration: 600